<?php
/**
 * This class has been auto-generated by PHP-DI.
 */
class CompiledContainer extends DI\CompiledContainer{
    const METHOD_MAPPING = array (
  'Nyholm\\Psr7\\Factory\\Psr17Factory' => 'get5be6ccc65111b914180293',
  'psr17factory' => 'get5be6ccc65144a928174549',
  'Twig_Loader_Filesystem' => 'get5be6ccc651460810756595',
  'loader' => 'get5be6ccc651493694588754',
  'Twig_Environment' => 'get5be6ccc65149c682991136',
  'SubEntry5be6ccc6514ab' => 'get5be6ccc6514ad718118531',
  'SubEntry5be6ccc6514b5' => 'get5be6ccc6514b6972500297',
  'twig' => 'get5be6ccc6514cf873272672',
  'App\\Controller\\Controller' => 'get5be6ccc6514d4807325760',
  'SubEntry5be6ccc65153c' => 'get5be6ccc65153e903670553',
  'SubEntry5be6ccc651547' => 'get5be6ccc651548641350281',
);

    protected function get5be6ccc65111b914180293()
    {
        $object = new Nyholm\Psr7\Factory\Psr17Factory();
        return $object;
    }

    protected function get5be6ccc65144a928174549()
    {
        return $this->delegateContainer->get('Nyholm\\Psr7\\Factory\\Psr17Factory');
    }

    protected function get5be6ccc651460810756595()
    {
        $object = new Twig_Loader_Filesystem('/srv/http/grease-php/public/../app/View/', NULL);
        return $object;
    }

    protected function get5be6ccc651493694588754()
    {
        return $this->delegateContainer->get('Twig_Loader_Filesystem');
    }

    protected function get5be6ccc6514ad718118531()
    {
        return $this->delegateContainer->get('loader');
    }

    protected function get5be6ccc6514b6972500297()
    {
        return [
            'cache' => '/srv/http/grease-php/public/../tmp/views',
        ];
    }

    protected function get5be6ccc65149c682991136()
    {
        $object = new Twig_Environment($this->get5be6ccc6514ad718118531(), $this->get5be6ccc6514b6972500297());
        return $object;
    }

    protected function get5be6ccc6514cf873272672()
    {
        return $this->delegateContainer->get('Twig_Environment');
    }

    protected function get5be6ccc65153e903670553()
    {
        return $this->delegateContainer->get('psr17factory');
    }

    protected function get5be6ccc651548641350281()
    {
        return $this->delegateContainer->get('twig');
    }

    protected function get5be6ccc6514d4807325760()
    {
        $object = new App\Controller\Controller($this->get5be6ccc65153e903670553(), $this->get5be6ccc651548641350281());
        return $object;
    }

}
